### ISSUE TITLE
Jest test always failing

### ISSUE THREAD

**Issue by jericbas** [react-lds/react-lds#419]
I'm getting this error every time I run my unit test

```javascript
lodash-es/omit.js:1 
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import arrayMap from './_arrayMap.js';
```

**Comment by fspoettel** [comment]
This is `node` not understanding the `import` / `export` statements in `lodash-es` and hence failing when encountering them.

Are you using `babel` in your project? If so, a possible workaround is installing `babel-jest` as a dev dependency and setting this in your `package.json`:

``` js
  "jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!(react-lds|lodash-es)/)"
    ]
  },
```

We'll need to document this and look into ways to improve this without sacrificing _treeshaking_ for the `/es` imports. I'll keep you posted on this ticket. 

Sorry for the trouble! Let us know if the workaround outlined above worked for you.

**Comment by fspoettel** [comment]
Closing: no requester response
